spring.datasource.url=jdbc:mysql://localhost:3306/examen_bd
spring.datasource.username=root
spring.datasource.password=Angelica
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=ClaveSecretaSuperSeguraParaElExamenFinal2026