spring.datasource.url=${MYSQL_URL}
spring.datasource.username=root
spring.datasource.password=${MYSQL_ROOT_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=ClaveSecretaSuperSeguraParaElExamenFinal2026